version: "3.9"
networks:
  laravel:

services:
  web:
    build: ./.docker/web
    restart: always
    container_name: laravel_app_nginx
    ports:
      - "8081:80"
    volumes:
      - "./:/var/www"
    networks:
      - laravel

  mysql:
    image: mysql:8
    container_name: laravel_app_mysql
    ports:
      - "3306:3306"
    volumes:
      - "./.docker/database:/var/lib/mysql"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: toor
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_SERVICE_NAME: mysql
    networks:
      - laravel

  php:
    build: ./.docker/php
    container_name: laravel_app_php
    volumes:
      - "./:/var/www"
    networks:
      - laravel
